### ISSUE TITLE
使用的时候发现判定 parentsHasHidden($this)为true

### ISSUE THREAD

**Issue by aboelf** [Dreamer365/FunLazy#2]
var hasHidden = false;
    var parent = null;
这两个变量在执行FunLazy函数的时候是否需要重新赋值？

**Comment by Dreamer365** [comment]
parentsHasHidden( $this ) 说明懒加载元素的祖先元素中存在隐藏元素，按照目前的懒加载机制，将无法执行懒加载操作。
